image: Visual Studio 2019

stack: node 18

branches:
  only:
    - main 

cache: node_modules  

install:
  - npm install  

build: off  

build_script:
  - npm run build    

deploy_script: 
  - git config --global user.email "ci@appveyor.com"
  - git config --global user.name "AppVeyor"
  - git remote set-url origin https://x-access-token:%GITHUB_TOKEN%@github.com/waanh/loading-ui.git
  - npx push-dir --dir=dist --branch=gh-pages --remote=https://x-access-token:%GITHUB_TOKEN%@github.com/waanh/loading-ui.git --force --verbose
